# Generated by Django 3.2.2 on 2021-05-14 05:57

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('clgeapp', '0002_alter_college_college_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='college_status',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('naac', 'NAAC'), ('nba', 'NBA'), ('none', 'NONE')], max_length=10),
        ),
    ]
